// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"cloud-disk/user-rpc/internal/logic"
	"cloud-disk/user-rpc/internal/svc"
	"cloud-disk/user-rpc/pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

// 用户注册
func (s *UsercenterServer) GetUserRegister(ctx context.Context, in *pb.GetUserRegisterReq) (*pb.GetUserRegisterResp, error) {
	l := logic.NewGetUserRegisterLogic(ctx, s.svcCtx)
	return l.GetUserRegister(in)
}

// 用户登录
func (s *UsercenterServer) GetUserLogin(ctx context.Context, in *pb.GetUserLoginReq) (*pb.GetUserLoginResp, error) {
	l := logic.NewGetUserLoginLogic(ctx, s.svcCtx)
	return l.GetUserLogin(in)
}

// 发送验证码
func (s *UsercenterServer) GetUserSendCode(ctx context.Context, in *pb.GetUserSendCodeReq) (*pb.GetUserSendCodeResp, error) {
	l := logic.NewGetUserSendCodeLogic(ctx, s.svcCtx)
	return l.GetUserSendCode(in)
}

// 发送文件
func (s *UsercenterServer) GetFileUpload(ctx context.Context, in *pb.GetFileUploadReq) (*pb.GetFileUploadResp, error) {
	l := logic.NewGetFileUploadLogic(ctx, s.svcCtx)
	return l.GetFileUpload(in)
}

// 关联用户数据库
func (s *UsercenterServer) GetUserRepositorySave(ctx context.Context, in *pb.GetUserRepositorySaveReq) (*pb.GetUserRepositorySaveResp, error) {
	l := logic.NewGetUserRepositorySaveLogic(ctx, s.svcCtx)
	return l.GetUserRepositorySave(in)
}

// 列出文件情况
func (s *UsercenterServer) GetUserFileList(ctx context.Context, in *pb.GetUserFileListReq) (*pb.GetUserFileListResp, error) {
	l := logic.NewGetUserFileListLogic(ctx, s.svcCtx)
	return l.GetUserFileList(in)
}

// 更新文件
func (s *UsercenterServer) GetUserFileUpdate(ctx context.Context, in *pb.GetUserFileUpdateReq) (*pb.GetUserFileUpdateResp, error) {
	l := logic.NewGetUserFileUpdateLogic(ctx, s.svcCtx)
	return l.GetUserFileUpdate(in)
}

// 创建文件夹
func (s *UsercenterServer) GetUserFolderCreate(ctx context.Context, in *pb.GetUserFolderCreateReq) (*pb.GetUserFolderCreateResp, error) {
	l := logic.NewGetUserFolderCreateLogic(ctx, s.svcCtx)
	return l.GetUserFolderCreate(in)
}

// 文件删除
func (s *UsercenterServer) GetUserFileDelete(ctx context.Context, in *pb.GetUserFileDeleteReq) (*pb.GetUserFileDeleteResp, error) {
	l := logic.NewGetUserFileDeleteLogic(ctx, s.svcCtx)
	return l.GetUserFileDelete(in)
}

// 刷新token
func (s *UsercenterServer) GetUserRefreshToken(ctx context.Context, in *pb.GetUserRefreshTokenReq) (*pb.GetUserRefreshTokenResp, error) {
	l := logic.NewGetUserRefreshTokenLogic(ctx, s.svcCtx)
	return l.GetUserRefreshToken(in)
}

// 分片上传准备
func (s *UsercenterServer) GetUserUploadPrepare(ctx context.Context, in *pb.GetUserUploadPrepareReq) (*pb.GetUserUploadPrepareResp, error) {
	l := logic.NewGetUserUploadPrepareLogic(ctx, s.svcCtx)
	return l.GetUserUploadPrepare(in)
}

// 分片上传
func (s *UsercenterServer) GetUserFileUploadChunk(ctx context.Context, in *pb.GetUserFileUploadChunkReq) (*pb.GetUserFileUploadChunkResp, error) {
	l := logic.NewGetUserFileUploadChunkLogic(ctx, s.svcCtx)
	return l.GetUserFileUploadChunk(in)
}

// 分片上传完成
func (s *UsercenterServer) GetUserFileUploadChunkComplete(ctx context.Context, in *pb.GetUserFileUploadChunkCompleteReq) (*pb.GetUserFileUploadChunkCompleteResp, error) {
	l := logic.NewGetUserFileUploadChunkCompleteLogic(ctx, s.svcCtx)
	return l.GetUserFileUploadChunkComplete(in)
}
