// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userRepositoryFieldNames          = builder.RawFieldNames(&UserRepository{})
	userRepositoryRows                = strings.Join(userRepositoryFieldNames, ",")
	userRepositoryRowsExpectAutoSet   = strings.Join(stringx.Remove(userRepositoryFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userRepositoryRowsWithPlaceHolder = strings.Join(stringx.Remove(userRepositoryFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	userRepositoryModel interface {
		Insert(ctx context.Context, data *UserRepository) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserRepository, error)
		Update(ctx context.Context, data *UserRepository) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserRepositoryModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserRepository struct {
		Id                 uint64         `db:"id"`
		Identity           sql.NullString `db:"identity"`
		UserIdentity       sql.NullString `db:"user_identity"`
		ParentId           sql.NullInt64  `db:"parent_id"`
		RepositoryIdentity sql.NullString `db:"repository_identity"`
		Ext                sql.NullString `db:"ext"` // 文件或文件夹类型
		Name               sql.NullString `db:"name"`
		CreatedAt          sql.NullTime   `db:"created_at"`
		UpdatedAt          sql.NullTime   `db:"updated_at"`
		DeletedAt          sql.NullTime   `db:"deleted_at"`
	}
)

func newUserRepositoryModel(conn sqlx.SqlConn) *defaultUserRepositoryModel {
	return &defaultUserRepositoryModel{
		conn:  conn,
		table: "`user_repository`",
	}
}

func (m *defaultUserRepositoryModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserRepositoryModel) FindOne(ctx context.Context, id uint64) (*UserRepository, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRepositoryRows, m.table)
	var resp UserRepository
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRepositoryModel) Insert(ctx context.Context, data *UserRepository) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userRepositoryRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Identity, data.UserIdentity, data.ParentId, data.RepositoryIdentity, data.Ext, data.Name, data.CreatedAt, data.UpdatedAt, data.DeletedAt)
	return ret, err
}

func (m *defaultUserRepositoryModel) Update(ctx context.Context, data *UserRepository) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRepositoryRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Identity, data.UserIdentity, data.ParentId, data.RepositoryIdentity, data.Ext, data.Name, data.CreatedAt, data.UpdatedAt, data.DeletedAt, data.Id)
	return err
}

func (m *defaultUserRepositoryModel) tableName() string {
	return m.table
}
